services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.12.3
    container_name: homepage
    restart: unless-stopped
    ports:
      - "127.0.0.1:3005:3000"
    environment:
      PUID: "1000"
      PGID: "1000"
      HOMEPAGE_ALLOWED_HOSTS: "127.0.0.1:3005,localhost:3005"
    volumes:
      - ./config:/app/config
    extra_hosts:
      - "host.docker.internal:host-gateway"

